Repository meowtive/meowtive, pull requests merged in 2025-01, with the labels that each got.

#31 feat: theme screen
  app/components/QuoteShareImage/styles.ts
  app/components/ThemeBackdrop/ThemeBackdrop.tsx
  app/components/ThemeBackdrop/styles.ts
  app/components/ThemeImage/ThemeImage.tsx
  app/components/ThemeImage/styles.ts
  app/components/index.ts
  app/resources/assets/images/social-share-background.png
  app/resources/assets/images/theme-1.png
  app/resources/assets/images/theme-2.png
  app/resources/assets/images/theme-3.png
  app/resources/assets/images/theme-4.png
  app/resources/assets/images/theme-5.png
  app/resources/assets/images/theme-6.png
  app/resources/strings/en.ts
  app/resources/strings/es.ts
  app/resources/strings/pt.ts
  app/routes/Routes.tsx
  app/screens/FavoritesScreen/FavoritesScreen.tsx
  app/screens/HomeScreen/HomeScreen.tsx
  app/screens/HomeScreen/styles.ts
  app/screens/ThemeScreen/ThemeScreen.tsx
  app/screens/ThemeScreen/styles.ts
  app/screens/index.ts
Labels: feature

#33 feat: translate app bottom tabs
  app/resources/strings/en.ts
  app/resources/strings/es.ts
  app/resources/strings/pt.ts
  app/routes/Routes.tsx
Labels: feature

#34 fix: use react useTranslation hook instead direct usage i18next.t on bottom-tabs
  app/routes/Routes.tsx
Labels: maintenance

#35 fix: move translation hook from out to inside component
  app/routes/Routes.tsx
Labels: bug
