Repository meowtive/meowtive, pull requests merged in 2025-02, with the labels that each got.

#39 fix(android): replace deprecated showPopupMenu
  App.tsx
  app/components/FavoritesItem/FavoritesItem.tsx
  app/components/FavoritesOptionsMenu/FavoritesOptionsMenu.tsx
  app/components/index.ts
  app/screens/HomeScreen/HomeScreen.tsx
  babel.config.js
  package.json
  yarn.lock
Labels: maintenance

#38 build(deps): update react native to v0.76.6 and too some libraries
  .yarnrc.yml
  App.tsx
  Gemfile
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/meowtive/MainApplication.kt
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  app/components/FavoritesItem/FavoritesItem.tsx
  app/components/FavoritesOptionsMenu/FavoritesOptionsMenu.tsx
  app/components/index.ts
  app/screens/HomeScreen/HomeScreen.tsx
  app/screens/ThemeScreen/ThemeScreen.tsx
  babel.config.js
  ios/Podfile.lock
  ios/meowtive.xcodeproj/project.pbxproj
  ios/meowtive/PrivacyInfo.xcprivacy
  package.json
  tsconfig.json
  yarn.lock
Labels: feature

#37 refactor: improvements to enhance app performance and structure
  App.tsx
  app/components/ErrorBoundary/ErrorBoundary.tsx
  app/components/FavoritesItem/FavoritesItem.tsx
  app/components/OnboardingButton/OnboardingButton.tsx
  app/components/ThemeImage/ThemeImage.tsx
  app/components/index.ts
  app/contexts/onboardingContext.ts
  app/libs/socialShare.ts
  app/resources/strings/en.ts
  app/resources/strings/es.ts
  app/resources/strings/pt.ts
  app/screens/HomeScreen/HomeScreen.tsx
  app/screens/OnboardingScreen/OnboardingScreen.tsx
  app/screens/ProfileScreen/ProfileScreen.tsx
  babel.config.js
  ios/Podfile.lock
  package.json
  tsconfig.json
  yarn.lock
Labels: bug, feature, maintenance

#40 feat: add restart app and improve errorBoundary
  App.tsx
  android/app/src/main/java/com/meowtive/MainApplication.kt
  android/build.gradle
  android/settings.gradle
  app/components/ErrorBoundary/ErrorBoundary.tsx
  app/components/OnboardingImages/OnboardingImages.tsx
  app/resources/strings/en.ts
  app/resources/strings/es.ts
  app/resources/strings/pt.ts
  app/utils/restartApp.ts
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: feature
